export default [
    {
        'id': 694919,
        'poster_path': 'https://image.tmdb.org/t/p/original//6CoRTJTmijhBLJTUNoVSUNxZMEI.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//pq0JSpwyT2URytdFG0euztQPAyR.jpg',
        'title': 'Money Plane',
        'average_rating': 6.625,
        'release_date': '2020-09-29',
        'overview': 'A professional thief with $40 million in debt and his family\'s life on the line must commit one final heist - rob a futuristic airborne casino filled with the world\'s most dangerous criminals.',
        'genres': [
            'Action',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 82,
        'tagline': '',
    },
    {
        'id': 337401,
        'poster_path': 'https://image.tmdb.org/t/p/original//aKx1ARwG55zZ0GpRvU2WrGrCG9o.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//zzWGRw277MNoCs3zhyG3YmYQsXv.jpg',
        'title': 'Mulan',
        'average_rating': 5.2727272727272725,
        'release_date': '2020-09-04',
        'overview': 'When the Emperor of China issues a decree that one man per family must serve in the Imperial Chinese Army to defend the country from Huns, Hua Mulan, the eldest daughter of an honored warrior, steps in to take the place of her ailing father. She is spirited, determined and quick on her feet. Disguised as a man by the name of Hua Jun, she is tested every step of the way and must harness her innermost strength and embrace her true potential.',
        'genres': [
            'Action',
            'Adventure',
            'Drama',
            'Fantasy',
        ],
        'budget': 200000000,
        'revenue': 57000000,
        'runtime': 115,
        'tagline': '',
    },
    {
        'id': 718444,
        'poster_path': 'https://image.tmdb.org/t/p/original//uOw5JD8IlD546feZ6oxbIjvN66P.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//x4UkhIQuHIJyeeOTdcbZ3t3gBSa.jpg',
        'title': 'Rogue',
        'average_rating': 6.166666666666667,
        'release_date': '2020-08-20',
        'overview': 'Battle-hardened O’Hara leads a lively mercenary team of soldiers on a daring mission: rescue hostages from their captors in remote Africa. But as the mission goes awry and the team is stranded, O’Hara’s squad must face a bloody, brutal encounter with a gang of rebels.',
        'genres': [
            'Action',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 106,
        'tagline': 'When the hunter becomes the prey.',
    },
    {
        'id': 539885,
        'poster_path': 'https://image.tmdb.org/t/p/original//qzA87Wf4jo1h8JMk9GilyIYvwsA.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//54yOImQgj8i85u9hxxnaIQBRUuo.jpg',
        'title': 'Ava',
        'average_rating': 5.142857142857143,
        'release_date': '2020-07-02',
        'overview': 'A black ops assassin is forced to fight for her own survival after a job goes dangerously wrong.',
        'genres': [
            'Action',
            'Crime',
            'Drama',
            'Thriller',
        ],
        'budget': 0,
        'revenue': 152812,
        'runtime': 96,
        'tagline': 'Kill. Or be killed.',
    },
    {
        'id': 581392,
        'poster_path': 'https://image.tmdb.org/t/p/original//sy6DvAu72kjoseZEjocnm2ZZ09i.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//gEjNlhZhyHeto6Fy5wWy5Uk3A9D.jpg',
        'title': 'Peninsula',
        'average_rating': 7.6,
        'release_date': '2020-07-15',
        'overview': 'A soldier and his team battle hordes of post-apocalyptic zombies in the wastelands of the Korean Peninsula.',
        'genres': [
            'Action',
            'Horror',
            'Thriller',
        ],
        'budget': 17000000,
        'revenue': 35878266,
        'runtime': 114,
        'tagline': 'Escape The Apocalypse',
    },
    {
        'id': 726739,
        'poster_path': 'https://image.tmdb.org/t/p/original//4BgSWFMW2MJ0dT5metLzsRWO7IJ.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//t22fWbzdnThPseipsdpwgdPOPCR.jpg',
        'title': 'Cats & Dogs 3: Paws Unite',
        'average_rating': 7,
        'release_date': '2020-10-02',
        'overview': 'It\'s been ten years since the creation of the Great Truce, an elaborate joint-species surveillance system designed and monitored by cats and dogs to keep the peace when conflicts arise. But when a tech-savvy villain hacks into wireless networks to use frequencies only heard by cats and dogs, he manipulates them into conflict and the worldwide battle between cats and dogs is BACK ON. Now, a team of inexperienced and untested agents will have to use their old-school animal instincts to restore order and peace between cats and dogs everywhere.',
        'genres': [
            'Comedy',
            'Action',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 84,
        'tagline': '',
    },
    {
        'id': 627290,
        'poster_path': 'https://image.tmdb.org/t/p/original//irkse1FMm9dWemwlxKJ7RINT9Iy.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//pGqBDYycGWsMYc57sYv5M9GAQoW.jpg',
        'title': 'Antebellum',
        'average_rating': 6.571428571428571,
        'release_date': '2020-09-02',
        'overview': 'Successful author Veronica finds herself trapped in a horrifying reality and must uncover the mind-bending mystery before it\'s too late.',
        'genres': [
            'Horror',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 105,
        'tagline': 'If it chooses you, nothing can save you.',
    },
    {
        'id': 613504,
        'poster_path': 'https://image.tmdb.org/t/p/original//kiX7UYfOpYrMFSAGbI6j1pFkLzQ.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//r5srC0cqU36n38azFnCyReEksiR.jpg',
        'title': 'After We Collided',
        'average_rating': 5.25,
        'release_date': '2020-09-02',
        'overview': 'Tessa finds herself struggling with her complicated relationship with Hardin; she faces a dilemma that could change their lives forever.',
        'genres': [
            'Romance',
            'Drama',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 105,
        'tagline': 'Can love overcome the past?',
    },
    {
        'id': 659986,
        'poster_path': 'https://image.tmdb.org/t/p/original//gzFatNrw0lhKD5NxaU6zC7S2KjP.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//xUUtcxWC6H48UCrpRwwSPQz69XC.jpg',
        'title': 'The Owners',
        'average_rating': 5.285714285714286,
        'release_date': '2020-09-04',
        'overview': 'A group of friends think they found the perfect easy score - an empty house with a safe full of cash. But when the elderly couple that lives there comes home early, the tables are suddenly turned. As a deadly game of cat and mouse ensues, the would-be thieves must fight to save themselves from a nightmare they could never have imagined.',
        'genres': [
            'Thriller',
            'Horror',
            'Action',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 92,
        'tagline': '',
    },
    {
        'id': 632618,
        'poster_path': 'https://image.tmdb.org/t/p/original//sDi6wKgECUjDug2gn4uODSqZ3yC.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//cVdYaAQmd5DZNdo0KFJruz7JpUs.jpg',
        'title': 'The Crimes That Bind',
        'average_rating': 4.857142857142857,
        'release_date': '2020-08-20',
        'overview': 'When her son is accused of raping and trying to murder his ex-wife, Alicia embarks on a journey that will change her life forever.',
        'genres': [
            'Thriller',
            'Crime',
            'Drama',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 99,
        'tagline': '',
    },
    {
        'id': 446893,
        'poster_path': 'https://image.tmdb.org/t/p/original//7W0G3YECgDAfnuiHG91r8WqgIOe.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//qsxhnirlp7y4Ae9bd11oYJSX59j.jpg',
        'title': 'Trolls World Tour',
        'average_rating': 5.5,
        'release_date': '2020-03-12',
        'overview': 'Queen Poppy and Branch make a surprising discovery — there are other Troll worlds beyond their own, and their distinct differences create big clashes between these various tribes. When a mysterious threat puts all of the Trolls across the land in danger, Poppy, Branch, and their band of friends must embark on an epic quest to create harmony among the feuding Trolls to unite them against certain doom.',
        'genres': [
            'Animation',
            'Family',
            'Comedy',
            'Fantasy',
            'Adventure',
            'Music',
        ],
        'budget': 0,
        'revenue': 1946164,
        'runtime': 91,
        'tagline': '',
    },
    {
        'id': 508439,
        'poster_path': 'https://image.tmdb.org/t/p/original//f4aul3FyD3jv3v4bul1IrkWZvzq.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//xFxk4vnirOtUxpOEWgA1MCRfy6J.jpg',
        'title': 'Onward',
        'average_rating': 6.4,
        'release_date': '2020-02-29',
        'overview': 'In a suburban fantasy world, two teenage elf brothers embark on an extraordinary quest to discover if there is still a little magic left out there.',
        'genres': [
            'Animation',
            'Family',
            'Adventure',
            'Comedy',
            'Fantasy',
        ],
        'budget': 200000000,
        'revenue': 103181419,
        'runtime': 102,
        'tagline': 'Their quest begineth.',
    },
    {
        'id': 479259,
        'poster_path': 'https://image.tmdb.org/t/p/original//vQgXwuJrlpzGDI8169tRQRy71Nv.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//wUP0KIAXcRevjjJpoSKT7LLhiaK.jpg',
        'title': 'Lost Girls & Love Hotels',
        'average_rating': 5.166666666666667,
        'release_date': '2020-09-18',
        'overview': 'Searching for escape in Tokyo\'s back alleys, a haunted English teacher explores love and lust with a dashing Yakuza, as their tumultuous affair takes her on a journey through the city\'s dive bars and three-hour love hotels.',
        'genres': [
            'Drama',
            'Thriller',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 97,
        'tagline': '',
    },
    {
        'id': 592350,
        'poster_path': 'https://image.tmdb.org/t/p/original//zGVbrulkupqpbwgiNedkJPyQum4.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//9guoVF7zayiiUq5ulKQpt375VIy.jpg',
        'title': 'My Hero Academia: Heroes Rising',
        'average_rating': 5.571428571428571,
        'release_date': '2019-12-20',
        'overview': 'Class 1-A visits Nabu Island where they finally get to do some real hero work. The place is so peaceful that it\'s more like a vacation … until they\'re attacked by a villain with an unfathomable Quirk! His power is eerily familiar, and it looks like Shigaraki had a hand in the plan. But with All Might retired and citizens\' lives on the line, there\'s no time for questions. Deku and his friends are the next generation of heroes, and they\'re the island\'s only hope.',
        'genres': [
            'Animation',
            'Action',
        ],
        'budget': 0,
        'revenue': 29900850,
        'runtime': 104,
        'tagline': '',
    },
    {
        'id': 531876,
        'poster_path': 'https://image.tmdb.org/t/p/original//hPkqY2EMqWUnFEoedukilIUieVG.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//n1RohH2VoK1CdVI2fXvcP19dSlm.jpg',
        'title': 'The Outpost',
        'average_rating': 3.8333333333333335,
        'release_date': '2020-06-24',
        'overview': 'A small unit of U.S. soldiers, alone at the remote Combat Outpost Keating, located deep in the valley of three mountains in Afghanistan, battles to defend against an overwhelming force of Taliban fighters in a coordinated attack. The Battle of Kamdesh, as it was known, was the bloodiest American engagement of the Afghan War in 2009 and Bravo Troop 3-61 CAV became one of the most decorated units of the 19-year conflict.',
        'genres': [
            'War',
            'Drama',
            'History',
            'Action',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 123,
        'tagline': 'The mission was survival.',
    },
    {
        'id': 499932,
        'poster_path': 'https://image.tmdb.org/t/p/original//7G2VvG1lU8q758uOqU6z2Ds0qpA.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//rUeqBuNDR9zN6vZV9kpEFMtQm0E.jpg',
        'title': 'The Devil All the Time',
        'average_rating': 4.666666666666667,
        'release_date': '2020-09-11',
        'overview': 'In Knockemstiff, Ohio and its neighboring backwoods, sinister characters converge around young Arvin Russell as he fights the evil forces that threaten him and his family.',
        'genres': [
            'Crime',
            'Drama',
            'Thriller',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 138,
        'tagline': 'Everyone ends up in the same damned place.',
    },
    {
        'id': 413518,
        'poster_path': 'https://image.tmdb.org/t/p/original//4w1ItwCJCTtSi9nPfJC1vU6NIVg.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//AdqOBPw4PdtzOcfEuQuZ8MNeTKb.jpg',
        'title': 'Pinocchio',
        'average_rating': 4.75,
        'release_date': '2019-12-19',
        'overview': 'In this live-action adaptation of the beloved fairytale, old woodcarver Geppetto fashions a wooden puppet, Pinocchio, who magically comes to life. Pinocchio longs for adventure and is easily led astray, encountering magical beasts, fantastical spectacles, while making friends and foes along his journey. However, his dream is to become a real boy, which can only come true if he finally changes his ways.',
        'genres': [
            'Fantasy',
            'Family',
            'Adventure',
            'Drama',
        ],
        'budget': 12400000,
        'revenue': 17133446,
        'runtime': 120,
        'tagline': 'The most beloved fairy tale comes to life',
    },
    {
        'id': 577922,
        'poster_path': 'https://image.tmdb.org/t/p/original//k68nPLbIST6NP96JmTxmZijEvCA.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//wzJRB4MKi3yK138bJyuL9nx47y6.jpg',
        'title': 'Tenet',
        'average_rating': 5.166666666666667,
        'release_date': '2020-08-22',
        'overview': 'Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.',
        'genres': [
            'Action',
            'Thriller',
            'Science Fiction',
        ],
        'budget': 205000000,
        'revenue': 239100000,
        'runtime': 150,
        'tagline': 'Time runs out.',
    },
    {
        'id': 619592,
        'poster_path': 'https://image.tmdb.org/t/p/original//ucktgbaMSaETUDLUBp1ubGD6aNj.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//eIqyISB5j99OSRZUuvdN9g2bBsS.jpg',
        'title': 'Force of Nature',
        'average_rating': 4.4,
        'release_date': '2020-07-02',
        'overview': 'A gang of thieves plan a heist during a hurricane and encounter trouble when a disgraced cop tries to force everyone in the building to evacuate.',
        'genres': [
            'Action',
            'Drama',
            'Crime',
        ],
        'budget': 0,
        'revenue': 215668,
        'runtime': 91,
        'tagline': '',
    },
    {
        'id': 501979,
        'poster_path': 'https://image.tmdb.org/t/p/original//4V2nTPfeB59TcqJcUfQ9ziTi7VN.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//oazPqs1z78LcIOFslbKtJLGlueo.jpg',
        'title': 'Bill & Ted Face the Music',
        'average_rating': 3.75,
        'release_date': '2020-08-27',
        'overview': 'Yet to fulfill their rock and roll destiny, the now middle-aged best friends Bill and Ted set out on a new adventure when a visitor from the future warns them that only their song can save life as we know it. Along the way, they are helped by their daughters, a new batch of historical figures and a few music legends—to seek the song that will set their world right and bring harmony to the universe.',
        'genres': [
            'Comedy',
            'Science Fiction',
            'Adventure',
        ],
        'budget': 25000000,
        'revenue': 0,
        'runtime': 92,
        'tagline': 'The future awaits',
    },
    {
        'id': 340102,
        'poster_path': 'https://image.tmdb.org/t/p/original//xrI4EnZWftpo1B7tTvlMUXVOikd.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//eCIvqa3QVCx6H09bdeOS8Al2Sqy.jpg',
        'title': 'The New Mutants',
        'average_rating': 4,
        'release_date': '2020-08-26',
        'overview': 'Five young mutants, just discovering their abilities while held in a secret facility against their will, fight to escape their past sins and save themselves.',
        'genres': [
            'Action',
            'Science Fiction',
            'Horror',
            'Adventure',
        ],
        'budget': 67000000,
        'revenue': 3100000,
        'runtime': 94,
        'tagline': 'It\'s time to face your demons',
    },
    {
        'id': 605499,
        'poster_path': 'https://image.tmdb.org/t/p/original//xIKVeH1iAKJOYYh9lvObD3hYIaf.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//48OhmVjmjqhB1TrevTMKwKUDetU.jpg',
        'title': 'Monsoon',
        'average_rating': 5.25,
        'release_date': '2020-09-25',
        'overview': 'Kit can’t remember much of his native Vietnam. When he returns to the Land of the Golden Star for the first time in over thirty years, he takes in his local surroundings as any Western tourist would, and the environment is as exotic as the language is incomprehensible. The aim of Kit’s travels – to find a place to scatter his parents’ ashes – thus becomes part of a journey back to his roots and to the discovery of his identity, which external circumstances have rendered ambiguous and complex.',
        'genres': [
            'Drama',
            'Romance',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 85,
        'tagline': '',
    },
    {
        'id': 737568,
        'poster_path': 'https://image.tmdb.org/t/p/original//pklyUbh4k1DbHdnsOMASyw7C6NH.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//9pHxv7TX0jOKNgnGMDP6RJ2m1GL.jpg',
        'title': 'The Doorman',
        'average_rating': 5.75,
        'release_date': '2020-10-01',
        'overview': 'A former Marine turned doorman at a luxury New York City high-rise must outsmart and battle a group of art thieves and their ruthless leader — while struggling to protect her sister\'s family. As the thieves become increasingly desperate and violent, the doorman calls upon her deadly fighting skills to end the showdown.',
        'genres': [
            'Action',
            'Thriller',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 97,
        'tagline': 'Be careful who you trust.',
    },
    {
        'id': 400160,
        'poster_path': 'https://image.tmdb.org/t/p/original//gxK2lB1w8an5ViPXzisDsRsyHr0.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//bt4xA9WZE9P1wiRILRFt0Zh2wmV.jpg',
        'title': 'The SpongeBob Movie: Sponge on the Run',
        'average_rating': 5.2,
        'release_date': '2020-08-14',
        'overview': 'After SpongeBob\'s beloved pet snail Gary is snail-napped, he and Patrick embark on an epic adventure to The Lost City of Atlantic City to bring Gary home.',
        'genres': [
            'Fantasy',
            'Animation',
            'Adventure',
            'Comedy',
            'Family',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 91,
        'tagline': 'A Huge Journey to Find a Tiny Friend',
    },
    {
        'id': 579583,
        'poster_path': 'https://image.tmdb.org/t/p/original//zQFjMmE3K9AX5QrBL1SXIxYQ9jz.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//5rwcd24GGltKiqdPT4G2dmchLr9.jpg',
        'title': 'The King of Staten Island',
        'average_rating': 6.8,
        'release_date': '2020-07-22',
        'overview': 'Scott has been a case of arrested development ever since his firefighter father died when he was seven. He’s now reached his mid-20s having achieved little, chasing a dream of becoming a tattoo artist that seems far out of reach. As his ambitious younger sister heads off to college, Scott is still living with his exhausted ER nurse mother and spends his days smoking weed, hanging with the guys — Oscar, Igor and Richie — and secretly hooking up with his childhood friend Kelsey. But when his mother starts dating a loudmouth firefighter named Ray, it sets off a chain of events that will force Scott to grapple with his grief and take his first tentative steps toward moving forward in life.',
        'genres': [
            'Comedy',
            'Drama',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 137,
        'tagline': '',
    },
    {
        'id': 597398,
        'poster_path': 'https://image.tmdb.org/t/p/original//c59eplVELdwrUfGBUAZVin3HfaL.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//ccwPF5jN09S4Cz7u6qs3T2yKOpO.jpg',
        'title': 'Away',
        'average_rating': 4.2,
        'release_date': '2019-11-15',
        'overview': 'After suffering a plane crash on a mysterious island, a young man embarks on an epic journey through forests, deserts and mountains trying to escape the shadow of a huge dark spirit.',
        'genres': [
            'Animation',
            'Adventure',
            'Fantasy',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 75,
        'tagline': '',
    },
    {
        'id': 617708,
        'poster_path': 'https://image.tmdb.org/t/p/original//yVsINl4Aa9vvQ9lE2LF77qNj7AP.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//oj9pEWQq5higRzKWiE8f0d5hBSb.jpg',
        'title': 'La llorona',
        'average_rating': 4.5,
        'release_date': '2020-01-22',
        'overview': 'A tale of horror and fantasy, ripe with suspense, and an urgent metaphor of Guatemalan recent history and its unhealed political wounds.',
        'genres': [
            'Thriller',
            'Horror',
            'Drama',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 97,
        'tagline': 'The past will haunt you.',
    },
    {
        'id': 528085,
        'poster_path': 'https://image.tmdb.org/t/p/original//7D430eqZj8y3oVkLFfsWXGRcpEG.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//5UkzNSOK561c2QRy2Zr4AkADzLT.jpg',
        'title': '2067',
        'average_rating': 5,
        'release_date': '2020-10-01',
        'overview': 'A lowly utility worker is called to the future by a mysterious radio signal, he must leave his dying wife to embark on a journey that will force him to face his deepest fears in an attempt to change the fabric of reality and save humankind from its greatest environmental crisis yet.',
        'genres': [
            'Science Fiction',
            'Thriller',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 114,
        'tagline': 'The fight for the future has begun.',
    },
    {
        'id': 610201,
        'poster_path': 'https://image.tmdb.org/t/p/original//jkAZb9jteax1XRnEFlCU9Oer1YJ.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//ruXHUA3KiiLEjCwvSqKuxe9O6ZQ.jpg',
        'title': 'The Pale Door',
        'average_rating': 3,
        'release_date': '2020-08-21',
        'overview': 'The Dalton gang escape to a nearby town after a train robbery goes south, but they are met by a coven of witches with sinister plans for the unsuspecting outlaws.',
        'genres': [
            'Horror',
            'Western',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 96,
        'tagline': 'It was the perfect score. But hell was their reward.',
    },
    {
        'id': 550231,
        'poster_path': 'https://image.tmdb.org/t/p/original//5mCqEeBA0MW7H6akFrFQXJu68rU.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//zRc6SG8V8WTTDrmZ78PgqjwYqoN.jpg',
        'title': 'The Secret: Dare to Dream',
        'average_rating': 5,
        'release_date': '2020-04-16',
        'overview': 'A widow with three children hires a handyman to fix her house during a major storm. When not doing home repairs, he shares his philosophy of believing in the power of the universe to deliver what we want.',
        'genres': [
            'Drama',
            'Romance',
        ],
        'budget': 21000000,
        'revenue': 0,
        'runtime': 107,
        'tagline': '',
    },
    {
        'id': 737173,
        'poster_path': 'https://image.tmdb.org/t/p/original//opZKcgocttEOAUzqluX3bUbbDew.jpg',
        'backdrop_path': 'https://www.esm.rochester.edu/uploads/NoPhotoAvailable.jpg',
        'title': 'Maratón After',
        'average_rating': 4.333333333333333,
        'release_date': '2020-09-03',
        'overview': '',
        'genres': [],
        'budget': 0,
        'revenue': 0,
        'runtime': 0,
        'tagline': '',
    },
    {
        'id': 737799,
        'poster_path': 'https://image.tmdb.org/t/p/original//tEvGSlRO0dz1pINzjSEELdTHvwk.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//ysGikUSBjG3NRSyycHPf4rsIXQm.jpg',
        'title': 'Maquis',
        'average_rating': 4.8,
        'release_date': '2020-08-28',
        'overview': '',
        'genres': [
            'Drama',
        ],
        'budget': 280000,
        'revenue': 0,
        'runtime': 0,
        'tagline': '',
    },
    {
        'id': 500840,
        'poster_path': 'https://image.tmdb.org/t/p/original//5ynWWapdl45hJXUh0KIevxSG9JQ.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//x3NqAzuTWvnron4pXXyFGkyTFo7.jpg',
        'title': 'I\'m Thinking of Ending Things',
        'average_rating': 6,
        'release_date': '2020-08-28',
        'overview': 'Nothing is as it seems when a woman experiencing misgivings about her new boyfriend joins him on a road trip to meet his parents at their remote farm.',
        'genres': [
            'Drama',
            'Thriller',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 135,
        'tagline': '',
    },
    {
        'id': 547017,
        'poster_path': 'https://image.tmdb.org/t/p/original//iSwTnNS7TKAS79Sz9LvyqlBxxrU.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//97UR8xPpUNqpvx5zr7eyf4YSBCE.jpg',
        'title': 'Shirley',
        'average_rating': 5.25,
        'release_date': '2020-09-11',
        'overview': 'A famous horror writer finds inspiration for her next book after she and her husband take in a young couple.',
        'genres': [
            'Drama',
            'Thriller',
        ],
        'budget': 0,
        'revenue': 73626,
        'runtime': 107,
        'tagline': '',
    },
    {
        'id': 449924,
        'poster_path': 'https://image.tmdb.org/t/p/original//swmjF0CQc59K3jdUFzOirXESeGN.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//hb3kjSQI0lwGUCIxnfAYec08VSq.jpg',
        'title': 'Ip Man 4: The Finale',
        'average_rating': 6,
        'release_date': '2019-12-19',
        'overview': 'Following the death of his wife, Ip Man travels to San Francisco to ease tensions between the local kung fu masters and his star student, Bruce Lee, while searching for a better future for his son.',
        'genres': [
            'Action',
            'Drama',
            'History',
        ],
        'budget': 52000000,
        'revenue': 0,
        'runtime': 105,
        'tagline': '',
    },
    {
        'id': 425001,
        'poster_path': 'https://image.tmdb.org/t/p/original//yUFbPtWeDbVR3zmqshOaL5lScyo.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//4gKyQ1McHa8ZKDsYoyKQSevF01J.jpg',
        'title': 'The War with Grandpa',
        'average_rating': 5.666666666666667,
        'release_date': '2020-01-31',
        'overview': 'Sixth-grader Peter is pretty much your average kid—he likes gaming, hanging with his friends and his beloved pair of Air Jordans. But when his recently widowed grandfather Ed  moves in with Peter’s family, the boy is forced to give up his most prized possession of all, his bedroom. Unwilling to let such an injustice stand, Peter devises a series of increasingly elaborate pranks to drive out the interloper, but Grandpa Ed won’t go without a fight.',
        'genres': [
            'Comedy',
            'Family',
            'Drama',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 94,
        'tagline': 'Old school vs new cool',
    },
    {
        'id': 582885,
        'poster_path': 'https://image.tmdb.org/t/p/original//ow3OA6OC0rjgbMVaLn2drwjvqZE.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//6j2g4fEAmjJqAclzprIpvz9Gaw4.jpg',
        'title': 'Cuties',
        'average_rating': 3.5,
        'release_date': '2020-08-19',
        'overview': 'Amy, an 11-year-old girl, joins a group of dancers named “the cuties” at school, and rapidly grows aware of her burgeoning femininity—upsetting her mother and her values in the process.',
        'genres': [
            'Drama',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 96,
        'tagline': '',
    },
    {
        'id': 659991,
        'poster_path': 'https://image.tmdb.org/t/p/original//erl30EcM8b8S84mvw8QXhNIeSfi.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//5nRyaVklxyA9OkxqZaPv1KBRqpd.jpg',
        'title': 'Made in Italy',
        'average_rating': 5,
        'release_date': '2020-08-06',
        'overview': 'A bohemian artist travels from London to Italy with his estranged son to sell the house they inherited from his late wife.',
        'genres': [
            'Comedy',
            'Drama',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 94,
        'tagline': '',
    },
    {
        'id': 501953,
        'poster_path': 'https://image.tmdb.org/t/p/original//2wXrBtfrvwMWE1i3iHjKjoRZjYk.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//oeaLQKoPFQxvhEz3yyR1QuestXG.jpg',
        'title': 'Eternal Beauty',
        'average_rating': 3,
        'release_date': '2020-08-21',
        'overview': 'When Jane is rejected by life, she spirals into a chaotic, schizophrenic world where love and normality collide with humorous consequences.',
        'genres': [
            'Comedy',
            'Drama',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 95,
        'tagline': 'Embrace different',
    },
    {
        'id': 585244,
        'poster_path': 'https://image.tmdb.org/t/p/original//dqA2FCzz4OMmXLitKopzf476RVB.jpg',
        'backdrop_path': 'https://image.tmdb.org/t/p/original//21Q8bzu10YF9i4O5amBkJBombYo.jpg',
        'title': 'I Still Believe',
        'average_rating': 3.8333333333333335,
        'release_date': '2020-03-12',
        'overview': 'The true-life story of Christian music star Jeremy Camp and his journey of love and loss that looks to prove there is always hope.',
        'genres': [
            'Drama',
            'Music',
        ],
        'budget': 0,
        'revenue': 0,
        'runtime': 115,
        'tagline': 'One love can change your life.',
    },
];